// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
